language: python
python: 3.5
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=pypy
  - TOXENV=flake827
  - TOXENV=flake834
install:
  - pip install tox
script:
  - tox
